name: eradko
description: A new Flutter project.
uses-material-design: true

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl:


dev_dependencies:
  flutter_test:
    sdk: flutter
  cupertino_icons: any
  font_awesome_flutter: 
  flutter_lints: 
  timeline_tile:
  google_fonts:
  url_launcher: 
  flutter_native_splash:
  provider:
  http:
  shared_preferences:
  another_flushbar:
  cached_network_image:
  shimmer:
  progress_indicators:
  photo_view: 
  video_player: 
  image_picker:
  google_sign_in:
  firebase_core:
  flutter_facebook_auth:
  favorite_button: 
  google_maps_flutter:
  pinput: 
  geolocator:
  fluttertoast:
  flutter_widget_from_html: 
  myfatoorah_flutter: 
  flutter_multi_formatter: 
  auth_buttons:
  stacked_firebase_auth:
  change_app_package_name: ^1.1.0


flutter_native_splash:
  background_image: "assets/image/splash/splash.png"
  fullscreen: true
  android: true
  ios: true
  web: true


flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/image/
    - assets/jsons/
    - assets/image/splash/
  fonts:
    - family: gessl
      fonts:
        - asset: fonts/GESSL.otf
    - family: gessm
      fonts:
        - asset: fonts/GESSM.otf
    - family: gessb
      fonts:
        - asset: fonts/GESSB.otf